version: '3.4'

services:
  postgresql:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  postgresql-test:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_USER: mxchange
      POSTGRES_PASSWORD: mxchange
      POSTGRES_DB: mx-db-test
    ports:
      - '5433:5432'
